services:
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: banco_pibd
    ports:
      - "5432:5432"
    volumes:
      - pgdata3:/var/lib/postgresql/data
      - ./banco.sql:/docker-entrypoint-initdb.d/banco.sql

volumes:
  pgdata3:
